# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98ef89eb513e2ce3e9b9b364387db589d7d11432fa2f53ce74f160ef516204c296f8ceadc35013e28b1cac09a623de1cee6c642be43c742ad71ef5943553c44

test:
  secret_key_base: f5894a32154405635b81db8ebf41034c6fba999ba4b83b9d2e8f663d241dde0a2199e7e7d371840a1d1b7d307d96047d8b4ecc1ec2fa734c75821f172a485fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
